### ISSUE TITLE
Generate code into Akka.Interfaced.CodeGen.cs

### ISSUE THREAD

**Issue by buihuuloc** [SaladLab/Chatty#1]
Hi there,

I just want to know that how can I generate my code into Akka.Interfaced.CodeGen file?

Thanks!

**Comment by veblush** [comment]
If you're using Visual Studio, it is automatically generated when project is being built.
But if you want to do it manually, you can use `CodeGenerator` used by this project and
you can see how to use it in project configuration.

**Comment by buihuuloc** [comment]
🆗 Thanks Kim
